<a href="https://colab.research.google.com/github/RatchanonPa/python_dataviz2024/blob/main/Data_Viz_2024_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Preprocessing**

In [16]:
import pandas as pd
import os

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [18]:
path = '/content/drive/MyDrive/data_viz_2024_DATA'

In [19]:
water_quality_file_path = os.path.join(path,'test-TidyData_2024.xlsx - water_quality.csv')
print(water_quality_file_path)

/content/drive/MyDrive/data_viz_2024_DATA/test-TidyData_2024.xlsx - water_quality.csv

In [20]:
water_df = pd.read_csv(water_quality_file_path)
water_df

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell,@dropdown
0,July_2018,1,1,0.095,0.012,0.027,30.2,5.54,622.7,330.3,545.2,4.37,0.173,0.053,0.013,1.635830e+05,NaN
1,July_2018,2,1,0.038,0.059,0.021,29.1,6.24,580.7,307.0,488.2,6.55,0.154,0.145,0.006,1.166667e+06,NaN
2,July_2018,3,1,0.044,0.089,0.023,29.7,5.52,547.1,289.4,462.2,5.67,0.153,0.154,0.014,2.970000e+06,NaN
3,July_2018,4,1,0.040,0.065,0.017,29.2,5.92,473.6,249.2,397.9,0.69,0.157,0.387,0.057,5.066670e+05,NaN
4,July_2018,5,1,0.045,0.062,0.023,29.5,5.79,685.5,366.0,581.2,4.46,0.204,0.043,0.007,1.265000e+06,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,July_2019,2,3,0.031,0.015,0.018,31.2,7.74,580.5,309.2,517.0,6.31,0.132,0.031,0.000,2.665833e+05,NaN
194,July_2019,3,3,0.024,0.020,0.016,29.7,7.50,513.0,272.6,436.0,3.00,0.230,0.059,0.000,6.428333e+05,NaN
195,July_2019,4,3,0.016,0.010,0.009,31.5,7.51,550.9,289.8,498.4,4.02,0.124,0.136,0.000,2.945000e+05,NaN
196,July_2019,5,3,0.015,0.012,0.010,28.5,7.31,540.6,287.4,443.4,1.53,0.110,0.056,0.000,3.470833e+05,NaN
197,July_2019,6,3,0.009,0.011,0.006,31.5,7.71,544.7,288.2,493.8,6.32,0.165,0.106,0.000,3.692500e+05,NaN

In [21]:
print(water_df.shape)
water_df.head(5)

(198, 17)

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell,@dropdown
0,July_2018,1,1,0.095,0.012,0.027,30.2,5.54,622.7,330.3,545.2,4.37,0.173,0.053,0.013,163583.0,NaN
1,July_2018,2,1,0.038,0.059,0.021,29.1,6.24,580.7,307.0,488.2,6.55,0.154,0.145,0.006,1166667.0,NaN
2,July_2018,3,1,0.044,0.089,0.023,29.7,5.52,547.1,289.4,462.2,5.67,0.153,0.154,0.014,2970000.0,NaN
3,July_2018,4,1,0.040,0.065,0.017,29.2,5.92,473.6,249.2,397.9,0.69,0.157,0.387,0.057,506667.0,NaN
4,July_2018,5,1,0.045,0.062,0.023,29.5,5.79,685.5,366.0,581.2,4.46,0.204,0.043,0.007,1265000.0,NaN

In [22]:
water_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   month          198 non-null    object
 1   station        198 non-null    int64
 2   rep.           198 non-null    int64
 3   Chlo_a         198 non-null    float64
 4   Chlo_b         198 non-null    float64
 5   total_Caro     198 non-null    float64
 6   Temp.          198 non-null    float64
 7   pH             198 non-null    float64
 8   EC             198 non-null    float64
 9   Salinity       198 non-null    float64
 10  TDS            198 non-null    float64
 11  DO             198 non-null    float64
 12  Nitrate        198 non-null    float64
 13  Ammonium       198 non-null    float64
 14  Phosphate      198 non-null    float64
 15  No.Algal_cell  198 non-null    float64
 16  @dropdown      0 non-null      float64
dtypes: float64(14), int64(2), object(1)
memory usage: 26.4+ KB

In [23]:
# prompt: drop column ' @dropdown'

water_df = water_df.drop(columns=['@dropdown'])
water_df

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell
0,July_2018,1,1,0.095,0.012,0.027,30.2,5.54,622.7,330.3,545.2,4.37,0.173,0.053,0.013,1.635830e+05
1,July_2018,2,1,0.038,0.059,0.021,29.1,6.24,580.7,307.0,488.2,6.55,0.154,0.145,0.006,1.166667e+06
2,July_2018,3,1,0.044,0.089,0.023,29.7,5.52,547.1,289.4,462.2,5.67,0.153,0.154,0.014,2.970000e+06
3,July_2018,4,1,0.040,0.065,0.017,29.2,5.92,473.6,249.2,397.9,0.69,0.157,0.387,0.057,5.066670e+05
4,July_2018,5,1,0.045,0.062,0.023,29.5,5.79,685.5,366.0,581.2,4.46,0.204,0.043,0.007,1.265000e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,July_2019,2,3,0.031,0.015,0.018,31.2,7.74,580.5,309.2,517.0,6.31,0.132,0.031,0.000,2.665833e+05
194,July_2019,3,3,0.024,0.020,0.016,29.7,7.50,513.0,272.6,436.0,3.00,0.230,0.059,0.000,6.428333e+05
195,July_2019,4,3,0.016,0.010,0.009,31.5,7.51,550.9,289.8,498.4,4.02,0.124,0.136,0.000,2.945000e+05
196,July_2019,5,3,0.015,0.012,0.010,28.5,7.31,540.6,287.4,443.4,1.53,0.110,0.056,0.000,3.470833e+05
197,July_2019,6,3,0.009,0.011,0.006,31.5,7.71,544.7,288.2,493.8,6.32,0.165,0.106,0.000,3.692500e+05

In [24]:
# prompt: แก้ค่าใน column 'month' โดยแก้จาก July เป็น Jul และ June เป็น Jun
water_df['month'] = water_df['month'].replace('July_2018', 'Jul_2018')
water_df['month'] = water_df['month'].replace('July_2019', 'Jul_2019')
water_df['month'] = water_df['month'].replace('June_2019', 'Jun_2019')
water_df

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell
0,Jul_2018,1,1,0.095,0.012,0.027,30.2,5.54,622.7,330.3,545.2,4.37,0.173,0.053,0.013,1.635830e+05
1,Jul_2018,2,1,0.038,0.059,0.021,29.1,6.24,580.7,307.0,488.2,6.55,0.154,0.145,0.006,1.166667e+06
2,Jul_2018,3,1,0.044,0.089,0.023,29.7,5.52,547.1,289.4,462.2,5.67,0.153,0.154,0.014,2.970000e+06
3,Jul_2018,4,1,0.040,0.065,0.017,29.2,5.92,473.6,249.2,397.9,0.69,0.157,0.387,0.057,5.066670e+05
4,Jul_2018,5,1,0.045,0.062,0.023,29.5,5.79,685.5,366.0,581.2,4.46,0.204,0.043,0.007,1.265000e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,Jul_2019,2,3,0.031,0.015,0.018,31.2,7.74,580.5,309.2,517.0,6.31,0.132,0.031,0.000,2.665833e+05
194,Jul_2019,3,3,0.024,0.020,0.016,29.7,7.50,513.0,272.6,436.0,3.00,0.230,0.059,0.000,6.428333e+05
195,Jul_2019,4,3,0.016,0.010,0.009,31.5,7.51,550.9,289.8,498.4,4.02,0.124,0.136,0.000,2.945000e+05
196,Jul_2019,5,3,0.015,0.012,0.010,28.5,7.31,540.6,287.4,443.4,1.53,0.110,0.056,0.000,3.470833e+05
197,Jul_2019,6,3,0.009,0.011,0.006,31.5,7.71,544.7,288.2,493.8,6.32,0.165,0.106,0.000,3.692500e+05

In [25]:
# Convert 'month' to datetime for easier manipulation
water_df['month'] = pd.to_datetime(water_df['month'], format='%b_%Y')

# Extract year from the 'month' column
water_df['year'] = water_df['month'].dt.year
water_df

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell,year
0,2018-07-01,1,1,0.095,0.012,0.027,30.2,5.54,622.7,330.3,545.2,4.37,0.173,0.053,0.013,1.635830e+05,2018
1,2018-07-01,2,1,0.038,0.059,0.021,29.1,6.24,580.7,307.0,488.2,6.55,0.154,0.145,0.006,1.166667e+06,2018
2,2018-07-01,3,1,0.044,0.089,0.023,29.7,5.52,547.1,289.4,462.2,5.67,0.153,0.154,0.014,2.970000e+06,2018
3,2018-07-01,4,1,0.040,0.065,0.017,29.2,5.92,473.6,249.2,397.9,0.69,0.157,0.387,0.057,5.066670e+05,2018
4,2018-07-01,5,1,0.045,0.062,0.023,29.5,5.79,685.5,366.0,581.2,4.46,0.204,0.043,0.007,1.265000e+06,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,2019-07-01,2,3,0.031,0.015,0.018,31.2,7.74,580.5,309.2,517.0,6.31,0.132,0.031,0.000,2.665833e+05,2019
194,2019-07-01,3,3,0.024,0.020,0.016,29.7,7.50,513.0,272.6,436.0,3.00,0.230,0.059,0.000,6.428333e+05,2019
195,2019-07-01,4,3,0.016,0.010,0.009,31.5,7.51,550.9,289.8,498.4,4.02,0.124,0.136,0.000,2.945000e+05,2019
196,2019-07-01,5,3,0.015,0.012,0.010,28.5,7.31,540.6,287.4,443.4,1.53,0.110,0.056,0.000,3.470833e+05,2019
197,2019-07-01,6,3,0.009,0.011,0.006,31.5,7.71,544.7,288.2,493.8,6.32,0.165,0.106,0.000,3.692500e+05,2019

In [26]:
# prompt: ตัดวันที่ออกให้เหลือแค่เดือนและปี

# Format the 'month' column to show only month and year
water_df['month'] = water_df['month'].dt.strftime('%b_%Y')
water_df

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell,year
0,Jul_2018,1,1,0.095,0.012,0.027,30.2,5.54,622.7,330.3,545.2,4.37,0.173,0.053,0.013,1.635830e+05,2018
1,Jul_2018,2,1,0.038,0.059,0.021,29.1,6.24,580.7,307.0,488.2,6.55,0.154,0.145,0.006,1.166667e+06,2018
2,Jul_2018,3,1,0.044,0.089,0.023,29.7,5.52,547.1,289.4,462.2,5.67,0.153,0.154,0.014,2.970000e+06,2018
3,Jul_2018,4,1,0.040,0.065,0.017,29.2,5.92,473.6,249.2,397.9,0.69,0.157,0.387,0.057,5.066670e+05,2018
4,Jul_2018,5,1,0.045,0.062,0.023,29.5,5.79,685.5,366.0,581.2,4.46,0.204,0.043,0.007,1.265000e+06,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,Jul_2019,2,3,0.031,0.015,0.018,31.2,7.74,580.5,309.2,517.0,6.31,0.132,0.031,0.000,2.665833e+05,2019
194,Jul_2019,3,3,0.024,0.020,0.016,29.7,7.50,513.0,272.6,436.0,3.00,0.230,0.059,0.000,6.428333e+05,2019
195,Jul_2019,4,3,0.016,0.010,0.009,31.5,7.51,550.9,289.8,498.4,4.02,0.124,0.136,0.000,2.945000e+05,2019
196,Jul_2019,5,3,0.015,0.012,0.010,28.5,7.31,540.6,287.4,443.4,1.53,0.110,0.056,0.000,3.470833e+05,2019
197,Jul_2019,6,3,0.009,0.011,0.006,31.5,7.71,544.7,288.2,493.8,6.32,0.165,0.106,0.000,3.692500e+05,2019

# 1.หาความแตกต่างของ ค่าเฉลี่ย ของข้อมูล Chlo_a ทุกๆ station ระหว่างปี 2018 และ ปี 2019

In [27]:
# prompt: หาความแตกต่างของ ค่าเฉลี่ย ของข้อมูล Chlo_a ทุกๆ station ระหว่างปี 2018 และ ปี 2019

# Calculate mean Chlo_a for each station in 2018
chlo_a_2018 = water_df[water_df['year'] == 2018].groupby('station')['Chlo_a'].mean()

# Calculate mean Chlo_a for each station in 2019
chlo_a_2019 = water_df[water_df['year'] == 2019].groupby('station')['Chlo_a'].mean()

# Calculate the difference
difference = chlo_a_2019 - chlo_a_2018

difference

station
1   -0.034333
2   -0.020356
3   -0.030333
4   -0.025100
5   -0.023378
6   -0.028278
Name: Chlo_a, dtype: float64

In [28]:
# prompt: ทำให้เป็น dataframe โดยประกอบด้วย 3 คอลัมน์ คือ chlo_a_2018, chlo_a_2019, and difference.

import pandas as pd
# Create a DataFrame from the calculated values
difference_df = pd.DataFrame({
    'chlo_a_2018': chlo_a_2018,
    'chlo_a_2019': chlo_a_2019,
    'difference': difference
})

difference_df

         chlo_a_2018  chlo_a_2019  difference
station
1           0.052667     0.018333   -0.034333
2           0.048222     0.027867   -0.020356
3           0.053333     0.023000   -0.030333
4           0.046833     0.021733   -0.025100
5           0.043444     0.020067   -0.023378
6           0.043944     0.015667   -0.028278

# 2. สร้างตารางค่าเฉลี่ย Chlo_b ทุกๆ station ของแต่ละเดือน

In [29]:
# prompt: สร้างตารางค่าเฉลี่ย Chlo_b ทุกๆ station ของแต่ละเดือน แบ่ง station เป็น 6 columns

# สร้างตาราง Pivot Table
pivot_table = water_df.pivot_table(index='month', columns='station', values='Chlo_b', aggfunc='mean')

# แสดงผลลัพธ์
pivot_table

station          1         2         3         4         5         6
month
Apr_2019  0.051333  0.019333  0.031000  0.020333  0.027333  0.025667
Aug_2018  0.075667  0.065333  0.065333  0.061333  0.060000  0.063000
Dec_2018  0.069667  0.064333  0.080667  0.062000  0.070333  0.065667
Jan_2019  0.022667  0.015000  0.017667  0.012000  0.009667  0.014000
Jul_2018  0.046667  0.062667  0.073333  0.061333  0.064333  0.056000
Jul_2019  0.014667  0.013667  0.017333  0.009333  0.011000  0.010333
Jun_2019  0.020667  0.013333  0.013333  0.013667  0.014000  0.008667
May_2019  0.015667  0.028667  0.016000  0.015667  0.017000  0.023667
Nov_2018  0.076000  0.064667  0.098000  0.070667  0.064000  0.073333
Oct_2018  0.131667  0.122667  0.106333  0.091000  0.082333  0.079333
Sep_2018  0.064000  0.074667  0.076667  0.064667  0.061000  0.061667

In [30]:
# prompt: เรียง pivot table โดยเริ่มจาก Jul_2018 และสิ้นสุดที่ Jul_2019

# Sort the pivot table by month
pivot_table = pivot_table.reindex(['Jul_2018',
                                   'Aug_2018',
                                   'Sep_2018',
                                   'Oct_2018',
                                   'Nov_2018',
                                   'Dec_2018',
                                   'Jan_2019',
                                   'Apr_2019',
                                   'May_2019',
                                   'Jun_2019',
                                   'Jul_2019'])

# แสดงผลลัพธ์
pivot_table

station          1         2         3         4         5         6
month
Jul_2018  0.046667  0.062667  0.073333  0.061333  0.064333  0.056000
Aug_2018  0.075667  0.065333  0.065333  0.061333  0.060000  0.063000
Sep_2018  0.064000  0.074667  0.076667  0.064667  0.061000  0.061667
Oct_2018  0.131667  0.122667  0.106333  0.091000  0.082333  0.079333
Nov_2018  0.076000  0.064667  0.098000  0.070667  0.064000  0.073333
Dec_2018  0.069667  0.064333  0.080667  0.062000  0.070333  0.065667
Jan_2019  0.022667  0.015000  0.017667  0.012000  0.009667  0.014000
Apr_2019  0.051333  0.019333  0.031000  0.020333  0.027333  0.025667
May_2019  0.015667  0.028667  0.016000  0.015667  0.017000  0.023667
Jun_2019  0.020667  0.013333  0.013333  0.013667  0.014000  0.008667
Jul_2019  0.014667  0.013667  0.017333  0.009333  0.011000  0.010333